// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/fwojciec/gqlmeetup"
	"sync"
)

var (
	lockDataLoaderServiceMockAuthorsListByAgentID sync.RWMutex
	lockDataLoaderServiceMockInitialize           sync.RWMutex
)

// Ensure, that DataLoaderServiceMock does implement gqlmeetup.DataLoaderService.
// If this is not the case, regenerate this file with moq.
var _ gqlmeetup.DataLoaderService = &DataLoaderServiceMock{}

// DataLoaderServiceMock is a mock implementation of gqlmeetup.DataLoaderService.
//
//     func TestSomethingThatUsesDataLoaderService(t *testing.T) {
//
//         // make and configure a mocked gqlmeetup.DataLoaderService
//         mockedDataLoaderService := &DataLoaderServiceMock{
//             AuthorsListByAgentIDFunc: func(ctx context.Context, agentID int64) ([]*gqlmeetup.Author, error) {
// 	               panic("mock out the AuthorsListByAgentID method")
//             },
//             InitializeFunc: func(ctx context.Context) context.Context {
// 	               panic("mock out the Initialize method")
//             },
//         }
//
//         // use mockedDataLoaderService in code that requires gqlmeetup.DataLoaderService
//         // and then make assertions.
//
//     }
type DataLoaderServiceMock struct {
	// AuthorsListByAgentIDFunc mocks the AuthorsListByAgentID method.
	AuthorsListByAgentIDFunc func(ctx context.Context, agentID int64) ([]*gqlmeetup.Author, error)

	// InitializeFunc mocks the Initialize method.
	InitializeFunc func(ctx context.Context) context.Context

	// calls tracks calls to the methods.
	calls struct {
		// AuthorsListByAgentID holds details about calls to the AuthorsListByAgentID method.
		AuthorsListByAgentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AgentID is the agentID argument value.
			AgentID int64
		}
		// Initialize holds details about calls to the Initialize method.
		Initialize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// AuthorsListByAgentID calls AuthorsListByAgentIDFunc.
func (mock *DataLoaderServiceMock) AuthorsListByAgentID(ctx context.Context, agentID int64) ([]*gqlmeetup.Author, error) {
	if mock.AuthorsListByAgentIDFunc == nil {
		panic("DataLoaderServiceMock.AuthorsListByAgentIDFunc: method is nil but DataLoaderService.AuthorsListByAgentID was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		AgentID int64
	}{
		Ctx:     ctx,
		AgentID: agentID,
	}
	lockDataLoaderServiceMockAuthorsListByAgentID.Lock()
	mock.calls.AuthorsListByAgentID = append(mock.calls.AuthorsListByAgentID, callInfo)
	lockDataLoaderServiceMockAuthorsListByAgentID.Unlock()
	return mock.AuthorsListByAgentIDFunc(ctx, agentID)
}

// AuthorsListByAgentIDCalls gets all the calls that were made to AuthorsListByAgentID.
// Check the length with:
//     len(mockedDataLoaderService.AuthorsListByAgentIDCalls())
func (mock *DataLoaderServiceMock) AuthorsListByAgentIDCalls() []struct {
	Ctx     context.Context
	AgentID int64
} {
	var calls []struct {
		Ctx     context.Context
		AgentID int64
	}
	lockDataLoaderServiceMockAuthorsListByAgentID.RLock()
	calls = mock.calls.AuthorsListByAgentID
	lockDataLoaderServiceMockAuthorsListByAgentID.RUnlock()
	return calls
}

// Initialize calls InitializeFunc.
func (mock *DataLoaderServiceMock) Initialize(ctx context.Context) context.Context {
	if mock.InitializeFunc == nil {
		panic("DataLoaderServiceMock.InitializeFunc: method is nil but DataLoaderService.Initialize was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockDataLoaderServiceMockInitialize.Lock()
	mock.calls.Initialize = append(mock.calls.Initialize, callInfo)
	lockDataLoaderServiceMockInitialize.Unlock()
	return mock.InitializeFunc(ctx)
}

// InitializeCalls gets all the calls that were made to Initialize.
// Check the length with:
//     len(mockedDataLoaderService.InitializeCalls())
func (mock *DataLoaderServiceMock) InitializeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockDataLoaderServiceMockInitialize.RLock()
	calls = mock.calls.Initialize
	lockDataLoaderServiceMockInitialize.RUnlock()
	return calls
}
