// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/fwojciec/gqlmeetup"
	"sync"
)

var (
	lockRepositoryMockAgentCreate   sync.RWMutex
	lockRepositoryMockAgentGetByID  sync.RWMutex
	lockRepositoryMockAgentsList    sync.RWMutex
	lockRepositoryMockAuthorCreate  sync.RWMutex
	lockRepositoryMockAuthorGetByID sync.RWMutex
	lockRepositoryMockAuthorsList   sync.RWMutex
	lockRepositoryMockBookGetByID   sync.RWMutex
	lockRepositoryMockBooksList     sync.RWMutex
)

// Ensure, that RepositoryMock does implement gqlmeetup.Repository.
// If this is not the case, regenerate this file with moq.
var _ gqlmeetup.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of gqlmeetup.Repository.
//
//     func TestSomethingThatUsesRepository(t *testing.T) {
//
//         // make and configure a mocked gqlmeetup.Repository
//         mockedRepository := &RepositoryMock{
//             AgentCreateFunc: func(ctx context.Context, data gqlmeetup.Agent) (*gqlmeetup.Agent, error) {
// 	               panic("mock out the AgentCreate method")
//             },
//             AgentGetByIDFunc: func(ctx context.Context, id int64) (*gqlmeetup.Agent, error) {
// 	               panic("mock out the AgentGetByID method")
//             },
//             AgentsListFunc: func(ctx context.Context) ([]*gqlmeetup.Agent, error) {
// 	               panic("mock out the AgentsList method")
//             },
//             AuthorCreateFunc: func(ctx context.Context, data gqlmeetup.Author) (*gqlmeetup.Author, error) {
// 	               panic("mock out the AuthorCreate method")
//             },
//             AuthorGetByIDFunc: func(ctx context.Context, id int64) (*gqlmeetup.Author, error) {
// 	               panic("mock out the AuthorGetByID method")
//             },
//             AuthorsListFunc: func(ctx context.Context) ([]*gqlmeetup.Author, error) {
// 	               panic("mock out the AuthorsList method")
//             },
//             BookGetByIDFunc: func(ctx context.Context, id int64) (*gqlmeetup.Book, error) {
// 	               panic("mock out the BookGetByID method")
//             },
//             BooksListFunc: func(ctx context.Context) ([]*gqlmeetup.Book, error) {
// 	               panic("mock out the BooksList method")
//             },
//         }
//
//         // use mockedRepository in code that requires gqlmeetup.Repository
//         // and then make assertions.
//
//     }
type RepositoryMock struct {
	// AgentCreateFunc mocks the AgentCreate method.
	AgentCreateFunc func(ctx context.Context, data gqlmeetup.Agent) (*gqlmeetup.Agent, error)

	// AgentGetByIDFunc mocks the AgentGetByID method.
	AgentGetByIDFunc func(ctx context.Context, id int64) (*gqlmeetup.Agent, error)

	// AgentsListFunc mocks the AgentsList method.
	AgentsListFunc func(ctx context.Context) ([]*gqlmeetup.Agent, error)

	// AuthorCreateFunc mocks the AuthorCreate method.
	AuthorCreateFunc func(ctx context.Context, data gqlmeetup.Author) (*gqlmeetup.Author, error)

	// AuthorGetByIDFunc mocks the AuthorGetByID method.
	AuthorGetByIDFunc func(ctx context.Context, id int64) (*gqlmeetup.Author, error)

	// AuthorsListFunc mocks the AuthorsList method.
	AuthorsListFunc func(ctx context.Context) ([]*gqlmeetup.Author, error)

	// BookGetByIDFunc mocks the BookGetByID method.
	BookGetByIDFunc func(ctx context.Context, id int64) (*gqlmeetup.Book, error)

	// BooksListFunc mocks the BooksList method.
	BooksListFunc func(ctx context.Context) ([]*gqlmeetup.Book, error)

	// calls tracks calls to the methods.
	calls struct {
		// AgentCreate holds details about calls to the AgentCreate method.
		AgentCreate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data gqlmeetup.Agent
		}
		// AgentGetByID holds details about calls to the AgentGetByID method.
		AgentGetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// AgentsList holds details about calls to the AgentsList method.
		AgentsList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// AuthorCreate holds details about calls to the AuthorCreate method.
		AuthorCreate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data gqlmeetup.Author
		}
		// AuthorGetByID holds details about calls to the AuthorGetByID method.
		AuthorGetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// AuthorsList holds details about calls to the AuthorsList method.
		AuthorsList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// BookGetByID holds details about calls to the BookGetByID method.
		BookGetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// BooksList holds details about calls to the BooksList method.
		BooksList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// AgentCreate calls AgentCreateFunc.
func (mock *RepositoryMock) AgentCreate(ctx context.Context, data gqlmeetup.Agent) (*gqlmeetup.Agent, error) {
	if mock.AgentCreateFunc == nil {
		panic("RepositoryMock.AgentCreateFunc: method is nil but Repository.AgentCreate was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data gqlmeetup.Agent
	}{
		Ctx:  ctx,
		Data: data,
	}
	lockRepositoryMockAgentCreate.Lock()
	mock.calls.AgentCreate = append(mock.calls.AgentCreate, callInfo)
	lockRepositoryMockAgentCreate.Unlock()
	return mock.AgentCreateFunc(ctx, data)
}

// AgentCreateCalls gets all the calls that were made to AgentCreate.
// Check the length with:
//     len(mockedRepository.AgentCreateCalls())
func (mock *RepositoryMock) AgentCreateCalls() []struct {
	Ctx  context.Context
	Data gqlmeetup.Agent
} {
	var calls []struct {
		Ctx  context.Context
		Data gqlmeetup.Agent
	}
	lockRepositoryMockAgentCreate.RLock()
	calls = mock.calls.AgentCreate
	lockRepositoryMockAgentCreate.RUnlock()
	return calls
}

// AgentGetByID calls AgentGetByIDFunc.
func (mock *RepositoryMock) AgentGetByID(ctx context.Context, id int64) (*gqlmeetup.Agent, error) {
	if mock.AgentGetByIDFunc == nil {
		panic("RepositoryMock.AgentGetByIDFunc: method is nil but Repository.AgentGetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	lockRepositoryMockAgentGetByID.Lock()
	mock.calls.AgentGetByID = append(mock.calls.AgentGetByID, callInfo)
	lockRepositoryMockAgentGetByID.Unlock()
	return mock.AgentGetByIDFunc(ctx, id)
}

// AgentGetByIDCalls gets all the calls that were made to AgentGetByID.
// Check the length with:
//     len(mockedRepository.AgentGetByIDCalls())
func (mock *RepositoryMock) AgentGetByIDCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	lockRepositoryMockAgentGetByID.RLock()
	calls = mock.calls.AgentGetByID
	lockRepositoryMockAgentGetByID.RUnlock()
	return calls
}

// AgentsList calls AgentsListFunc.
func (mock *RepositoryMock) AgentsList(ctx context.Context) ([]*gqlmeetup.Agent, error) {
	if mock.AgentsListFunc == nil {
		panic("RepositoryMock.AgentsListFunc: method is nil but Repository.AgentsList was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockRepositoryMockAgentsList.Lock()
	mock.calls.AgentsList = append(mock.calls.AgentsList, callInfo)
	lockRepositoryMockAgentsList.Unlock()
	return mock.AgentsListFunc(ctx)
}

// AgentsListCalls gets all the calls that were made to AgentsList.
// Check the length with:
//     len(mockedRepository.AgentsListCalls())
func (mock *RepositoryMock) AgentsListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockRepositoryMockAgentsList.RLock()
	calls = mock.calls.AgentsList
	lockRepositoryMockAgentsList.RUnlock()
	return calls
}

// AuthorCreate calls AuthorCreateFunc.
func (mock *RepositoryMock) AuthorCreate(ctx context.Context, data gqlmeetup.Author) (*gqlmeetup.Author, error) {
	if mock.AuthorCreateFunc == nil {
		panic("RepositoryMock.AuthorCreateFunc: method is nil but Repository.AuthorCreate was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data gqlmeetup.Author
	}{
		Ctx:  ctx,
		Data: data,
	}
	lockRepositoryMockAuthorCreate.Lock()
	mock.calls.AuthorCreate = append(mock.calls.AuthorCreate, callInfo)
	lockRepositoryMockAuthorCreate.Unlock()
	return mock.AuthorCreateFunc(ctx, data)
}

// AuthorCreateCalls gets all the calls that were made to AuthorCreate.
// Check the length with:
//     len(mockedRepository.AuthorCreateCalls())
func (mock *RepositoryMock) AuthorCreateCalls() []struct {
	Ctx  context.Context
	Data gqlmeetup.Author
} {
	var calls []struct {
		Ctx  context.Context
		Data gqlmeetup.Author
	}
	lockRepositoryMockAuthorCreate.RLock()
	calls = mock.calls.AuthorCreate
	lockRepositoryMockAuthorCreate.RUnlock()
	return calls
}

// AuthorGetByID calls AuthorGetByIDFunc.
func (mock *RepositoryMock) AuthorGetByID(ctx context.Context, id int64) (*gqlmeetup.Author, error) {
	if mock.AuthorGetByIDFunc == nil {
		panic("RepositoryMock.AuthorGetByIDFunc: method is nil but Repository.AuthorGetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	lockRepositoryMockAuthorGetByID.Lock()
	mock.calls.AuthorGetByID = append(mock.calls.AuthorGetByID, callInfo)
	lockRepositoryMockAuthorGetByID.Unlock()
	return mock.AuthorGetByIDFunc(ctx, id)
}

// AuthorGetByIDCalls gets all the calls that were made to AuthorGetByID.
// Check the length with:
//     len(mockedRepository.AuthorGetByIDCalls())
func (mock *RepositoryMock) AuthorGetByIDCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	lockRepositoryMockAuthorGetByID.RLock()
	calls = mock.calls.AuthorGetByID
	lockRepositoryMockAuthorGetByID.RUnlock()
	return calls
}

// AuthorsList calls AuthorsListFunc.
func (mock *RepositoryMock) AuthorsList(ctx context.Context) ([]*gqlmeetup.Author, error) {
	if mock.AuthorsListFunc == nil {
		panic("RepositoryMock.AuthorsListFunc: method is nil but Repository.AuthorsList was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockRepositoryMockAuthorsList.Lock()
	mock.calls.AuthorsList = append(mock.calls.AuthorsList, callInfo)
	lockRepositoryMockAuthorsList.Unlock()
	return mock.AuthorsListFunc(ctx)
}

// AuthorsListCalls gets all the calls that were made to AuthorsList.
// Check the length with:
//     len(mockedRepository.AuthorsListCalls())
func (mock *RepositoryMock) AuthorsListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockRepositoryMockAuthorsList.RLock()
	calls = mock.calls.AuthorsList
	lockRepositoryMockAuthorsList.RUnlock()
	return calls
}

// BookGetByID calls BookGetByIDFunc.
func (mock *RepositoryMock) BookGetByID(ctx context.Context, id int64) (*gqlmeetup.Book, error) {
	if mock.BookGetByIDFunc == nil {
		panic("RepositoryMock.BookGetByIDFunc: method is nil but Repository.BookGetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	lockRepositoryMockBookGetByID.Lock()
	mock.calls.BookGetByID = append(mock.calls.BookGetByID, callInfo)
	lockRepositoryMockBookGetByID.Unlock()
	return mock.BookGetByIDFunc(ctx, id)
}

// BookGetByIDCalls gets all the calls that were made to BookGetByID.
// Check the length with:
//     len(mockedRepository.BookGetByIDCalls())
func (mock *RepositoryMock) BookGetByIDCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	lockRepositoryMockBookGetByID.RLock()
	calls = mock.calls.BookGetByID
	lockRepositoryMockBookGetByID.RUnlock()
	return calls
}

// BooksList calls BooksListFunc.
func (mock *RepositoryMock) BooksList(ctx context.Context) ([]*gqlmeetup.Book, error) {
	if mock.BooksListFunc == nil {
		panic("RepositoryMock.BooksListFunc: method is nil but Repository.BooksList was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockRepositoryMockBooksList.Lock()
	mock.calls.BooksList = append(mock.calls.BooksList, callInfo)
	lockRepositoryMockBooksList.Unlock()
	return mock.BooksListFunc(ctx)
}

// BooksListCalls gets all the calls that were made to BooksList.
// Check the length with:
//     len(mockedRepository.BooksListCalls())
func (mock *RepositoryMock) BooksListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockRepositoryMockBooksList.RLock()
	calls = mock.calls.BooksList
	lockRepositoryMockBooksList.RUnlock()
	return calls
}
